import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  imports: [RouterModule,CommonModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss'
})
export class DashboardComponent {
  
  diseases:any = [
  {
    name: "Atelectasia",
    explanation: " Es una condición en la que una parte del pulmón colapsa o no se llena adecuadamente de aire, reduciendo la oxigenación del cuerpo. En una radiografía de tórax, suele observarse como zonas opacas o densas en el pulmón, desplazamiento de estructuras vecinas como el diafragma o el mediastino, y disminución del volumen pulmonar en la zona afectada.En el contexto del estudio ChestX-ray8, la atelectasia es una de las 8 enfermedades torácicas comunes seleccionadas por radiólogos del NIH para construir un sistema automatizado de detección mediante inteligencia artificial. Las imágenes utilizadas provienen de más de 32 mil pacientes, con etiquetas generadas automáticamente a partir de los informes médicos mediante técnicas de procesamiento de lenguaje natural (NLP).Para etiquetar las radiografías con atelectasia, se usaron herramientas como MetaMap y DNorm, combinadas con reglas sintácticas personalizadas que detectan negaciones y ambigüedades del lenguaje médico. Por ejemplo, se evita marcar como positiva una frase como “sin evidencia de atelectasia”.Una vez etiquetadas, las imágenes se usaron para entrenar modelos de redes neuronales profundas (DCNN) como ResNet-50, capaces de aprender patrones visuales en las radiografías que indican la presencia de atelectasia. Aunque el modelo no recibió ubicaciones exactas (bounding boxes) en todas las imágenes, logró aprender a identificar características típicas como zonas densas en lóbulos inferiores o colapsos parciales del pulmón.El modelo genera mapas de activación (heatmaps) que muestran las regiones con mayor probabilidad de contener atelectasia, permitiendo así una localización aproximada del problema. En pruebas con imágenes que sí tenían anotaciones manuales, la IA logró una precisión del 72.8% en detección, superando incluso a métodos previos como MetaMap.Gracias a este enfoque, es posible detectar automáticamente signos de atelectasia a gran escala, incluso con datos parcialmente etiquetados. Este tipo de sistema puede asistir a los profesionales médicos en el diagnóstico temprano y seguimiento de pacientes con afecciones respiratorias.",
    ruta: "img1.png"
  },
  {
    name: "Cardiomegalia",
    explanation: "Es el agrandamiento anormal del corazón, una señal que puede indicar enfermedades cardiovasculares como insuficiencia cardíaca, hipertensión crónica o miocardiopatías. En una radiografía de tórax, suele detectarse cuando el tamaño del corazón ocupa más de la mitad del ancho del tórax, conocido como un índice cardiotorácico elevado.En el estudio ChestX-ray8, la cardiomegalia fue una de las ocho enfermedades torácicas seleccionadas por especialistas debido a su relevancia clínica y visibilidad en radiografías. Las etiquetas se obtuvieron de forma automática usando procesamiento de lenguaje natural (NLP) sobre los informes médicos que acompañaban a más de 100 mil radiografías. Se utilizaron herramientas como DNorm y MetaMap, además de reglas sintácticas para excluir menciones negadas o inciertas (por ejemplo: “no hay signos de cardiomegalia”).El sistema de inteligencia artificial fue entrenado usando redes neuronales convolucionales profundas (DCNN), como ResNet-50, que aprendieron a identificar patrones visuales asociados a la cardiomegalia sin necesidad de que todas las imágenes tuvieran cajas delimitadoras manuales. Estos modelos generan mapas de activación que permiten localizar visualmente las regiones más relevantes, como la silueta cardíaca.Los resultados mostraron que la detección de cardiomegalia es una de las tareas mejor resueltas por el modelo, alcanzando un AUC (Área Bajo la Curva ROC) de 0.8141, lo que indica una alta precisión en la clasificación. En cuanto a localización, la IA logró una precisión superior al 99% al permitir una tolerancia amplia entre las predicciones y las cajas reales.Este sistema demuestra que, incluso sin anotaciones manuales detalladas, es posible entrenar modelos robustos para reconocer y localizar signos claros de enfermedades como la cardiomegalia, brindando soporte a los profesionales de salud en el diagnóstico automatizado a gran escala.",
    ruta: "img2.png"
  },
  {
    name: "Effusion",
    explanation: "El derrame pleural es la acumulación anormal de líquido entre las capas que recubren los pulmones y la cavidad torácica. Esta condición puede estar asociada a infecciones, insuficiencia cardíaca, cáncer o enfermedades pulmonares. En una radiografía de tórax, el derrame se observa como una opacidad homogénea en las bases pulmonares, pérdida del ángulo costofrénico y desplazamiento de estructuras adyacentes en casos severos.En el estudio ChestX-ray8, el derrame fue una de las ocho enfermedades torácicas seleccionadas para ser detectadas mediante inteligencia artificial, debido a su frecuencia y relevancia clínica. Las etiquetas se obtuvieron automáticamente de los informes médicos mediante técnicas de procesamiento de lenguaje natural (NLP). Se usaron herramientas como MetaMap y DNorm, así como reglas sintácticas avanzadas que identifican menciones afirmativas de derrame y descartan expresiones negadas o inciertas como “sin derrame pleural” o “posible derrame”.El sistema de IA se entrenó utilizando redes neuronales profundas (DCNN) como ResNet-50, que aprenden a reconocer patrones característicos de derrame pleural sin necesidad de cajas delimitadoras (bounding boxes) en todas las imágenes. Estas redes generan mapas de activación (heatmaps) que permiten visualizar las regiones con mayor probabilidad de contener la enfermedad.En la evaluación del modelo, el derrame fue una de las condiciones mejor detectadas, con un AUC de 0.7362, superando a otros hallazgos más sutiles como masas o nódulos. En cuanto a localización, la IA alcanzó una precisión de más del 71% con bajo margen de error (AFP 0.8), incluso cuando no se proporcionaron coordenadas precisas durante el entrenamiento.Gracias a su claridad visual en las radiografías, el derrame pleural es una de las enfermedades más efectivamente detectadas por el sistema de IA propuesto en ChestX-ray8, lo que lo convierte en un objetivo ideal para aplicaciones clínicas automatizadas y sistemas de apoyo al diagnóstico.",
    ruta: "img3.png"
  },
  {
    name: "Infiltración Pulmonar",
    explanation: "La infiltración pulmonar hace referencia a la presencia de material (líquido, células inflamatorias, sangre, etc.) dentro del tejido pulmonar, lo cual altera su aspecto normal. Puede estar asociada a infecciones (como neumonía), edema pulmonar, inflamaciones crónicas o procesos tumorales. En una radiografía de tórax, la infiltración suele verse como áreas difusas o parcheadas de opacidad, lo que puede dificultar su interpretación clínica.En el estudio ChestX-ray8, la infiltración fue una de las ocho enfermedades torácicas seleccionadas para el sistema de detección automática mediante inteligencia artificial, debido a su frecuencia y desafío diagnóstico. Las etiquetas se obtuvieron aplicando procesamiento de lenguaje natural (NLP) sobre informes médicos, usando herramientas como DNorm y MetaMap, combinadas con reglas de análisis sintáctico para excluir frases como “no hay evidencia de infiltrado” o “posible infiltración”.La IA fue entrenada con redes neuronales convolucionales profundas (DCNN), como ResNet-50, que aprendieron a detectar patrones difusos en las imágenes de tórax que podrían indicar infiltración. Aunque no todas las imágenes incluían cajas delimitadoras manuales, los modelos fueron capaces de generar mapas de activación que muestran las zonas más probables de afectación pulmonar.En cuanto a desempeño, la infiltración es una de las clases más representadas en el dataset (más de 10,000 imágenes), y la IA logró un AUC de 0.6128, mostrando un buen equilibrio entre sensibilidad y especificidad. En las pruebas de localización, el modelo alcanzó una precisión del 78.8% con márgenes tolerantes, aunque debido a su naturaleza difusa, el número de falsos positivos puede ser mayor que en otras patologías.La infiltración pulmonar es un reto tanto para humanos como para máquinas, ya que puede simular otras condiciones o estar presente de manera sutil. Aun así, el modelo de ChestX-ray8 logra resultados competitivos, convirtiéndose en una herramienta útil para apoyar el diagnóstico clínico y seguimiento de enfermedades pulmonares complejas.",
    ruta: "img4.png"
  },
  {
    name: "Masa Pulmonar ",
    explanation: "Una masa pulmonar es una lesión sólida en el pulmón, generalmente mayor a 3 cm, que puede representar una neoplasia (benigna o maligna), una infección localizada o un proceso inflamatorio crónico. En una radiografía de tórax, las masas suelen observarse como opacidades redondeadas o irregulares, con bordes bien definidos o mal delimitados según su naturaleza.En el estudio ChestX-ray8, la masa fue incluida como una de las ocho enfermedades torácicas seleccionadas para detección automatizada mediante inteligencia artificial, debido a su importancia clínica en el diagnóstico diferencial de tumores pulmonares. Las etiquetas de mass se extrajeron de los informes radiológicos mediante técnicas avanzadas de procesamiento de lenguaje natural (NLP), combinando las herramientas MetaMap y DNorm, y reglas sintácticas para evitar falsas detecciones por menciones negadas o inciertas como “no se observa masa” o “posible masa”.El sistema de IA fue entrenado con redes neuronales convolucionales profundas como ResNet-50, que aprendieron a detectar patrones visuales asociados a masas, a pesar de la gran variabilidad de forma, tamaño y ubicación que estas pueden presentar. Aunque las imágenes no contaban con anotaciones manuales detalladas, los modelos generaron mapas de activación (heatmaps) que indicaban regiones con alta probabilidad de contener una masa.En las evaluaciones, la detección de masas fue más desafiante en comparación con otras enfermedades, debido a su diversidad morfológica. El modelo alcanzó un AUC de 0.5609, reflejando esta dificultad. Sin embargo, en las pruebas de localización, se logró una precisión del 43.5% con márgenes amplios, suficiente para ubicar posibles lesiones y sugerir su análisis por parte de un radiólogo.A pesar de la complejidad visual de esta condición, el sistema de ChestX-ray8 logra identificar patrones sugestivos de masa pulmonar, convirtiéndose en una herramienta prometedora para apoyar el diagnóstico temprano de posibles lesiones tumorales.",
    ruta: "img5.png"
  },
  {
    name: "Nódulo Pulmonar",
    explanation: "Un nódulo pulmonar es una pequeña lesión redondeada u oval en el pulmón, generalmente menor a 3 cm de diámetro. Puede ser benigno (como un granuloma o hamartoma) o indicar una lesión maligna en etapa temprana. En las radiografías de tórax, los nódulos pueden aparecer como opacidades pequeñas, aisladas y bien delimitadas, aunque a veces pueden ser difíciles de distinguir por su tamaño y localización.En el dataset ChestX-ray8, el nódulo fue incluido como una de las ocho patologías torácicas comunes a detectar mediante inteligencia artificial. Las etiquetas fueron extraídas automáticamente desde los informes radiológicos usando herramientas de procesamiento de lenguaje natural (NLP) como MetaMap y DNorm, junto con reglas gramaticales que filtran menciones negadas o inciertas (por ejemplo: “no se evidencia nódulo” o “posible nódulo pulmonar”).El sistema de IA fue entrenado con redes neuronales profundas (DCNN), como ResNet-50, que aprendieron a reconocer los patrones visuales típicos de los nódulos pulmonares, aún cuando no se proporcionaron anotaciones manuales exactas para todas las imágenes. Gracias al uso de mapas de activación (heatmaps), el modelo puede identificar regiones de interés y sugerir la ubicación probable del nódulo.La detección de nódulos representa uno de los mayores retos para el modelo, ya que estas lesiones suelen ser pequeñas, con bajo contraste y gran variabilidad visual. Aun así, se alcanzó un AUC de 0.7164, lo que indica un desempeño razonablemente alto. En tareas de localización, la IA logró una precisión del 16.4% en configuraciones con baja tolerancia (IoBB ≥ 0.1), y se espera que este resultado mejore con técnicas adicionales como entrenamiento supervisado completo o segmentación más precisa.El nódulo pulmonar es clínicamente relevante por su potencial para detectar cáncer de pulmón en etapas tempranas. El sistema ChestX-ray8 demuestra ser una herramienta valiosa para señalar hallazgos sutiles que podrían pasar desapercibidos, ayudando a priorizar el análisis médico en contextos de alto volumen de imágenes.",
    ruta: "img6.png"
  },
  {
    name: "Neumonía",
    explanation: "La neumonía es una infección pulmonar que provoca la acumulación de líquido o pus en los alvéolos, lo que dificulta la respiración y reduce el intercambio de oxígeno. Puede ser causada por bacterias, virus u hongos, y en una radiografía de tórax suele manifestarse como opacidades localizadas o difusas, consolidaciones y pérdida de definición de las estructuras anatómicas normales del pulmón.En el estudio ChestX-ray8, la neumonía fue seleccionada como una de las ocho enfermedades torácicas clave a detectar mediante inteligencia artificial, a pesar de su baja representación en el dataset (menos del 1% de las imágenes). Las etiquetas se obtuvieron de los informes radiológicos usando procesamiento de lenguaje natural (NLP) con herramientas como MetaMap y DNorm, junto con reglas sintácticas que filtran menciones negadas o inciertas (por ejemplo: “no hay evidencia de neumonía” o “podría representar neumonía”).El modelo de IA fue entrenado con redes neuronales convolucionales profundas (DCNN), como ResNet-50, que aprendieron a identificar los patrones radiológicos típicos de la neumonía, incluso cuando las imágenes no tenían anotaciones precisas. Los mapas de activación (heatmaps) generados por el modelo ayudan a localizar las regiones pulmonares afectadas.Debido a la baja cantidad de imágenes etiquetadas con neumonía y a su variabilidad visual, esta clase fue una de las más desafiantes para el modelo. Aun así, se logró un AUC de 0.6333, lo que indica una capacidad de detección razonable. En pruebas de localización, la IA alcanzó una precisión del 75% al comparar con anotaciones manuales amplias, lo que demuestra su potencial para identificar esta condición en escenarios reales.La capacidad de un sistema automatizado como el de ChestX-ray8 para detectar signos de neumonía puede ser crucial en situaciones de alta demanda clínica o en regiones con recursos limitados, permitiendo priorizar casos sospechosos y mejorar el tiempo de atención médica.",
    ruta: "img7.png"
  },
  {
    name: "Neumotórax ",
    explanation: "El neumotórax es una condición en la que se acumula aire en el espacio pleural, provocando el colapso parcial o total del pulmón. Puede ocurrir de forma espontánea, por trauma o como complicación médica, y representa una urgencia clínica si compromete la función respiratoria. En una radiografía de tórax, se identifica por la presencia de una línea pleural visible sin marcas pulmonares más allá de ella, y a veces por el desplazamiento del mediastino.En el estudio ChestX-ray8, el neumotórax fue una de las ocho enfermedades torácicas seleccionadas para detección automática mediante inteligencia artificial, gracias a su importancia clínica y patrones radiográficos distintivos. Las etiquetas se extrajeron de los informes médicos utilizando procesamiento de lenguaje natural (NLP) con herramientas como MetaMap y DNorm, además de reglas gramaticales para descartar menciones negadas o inciertas como “no hay neumotórax” o “posible neumotórax”.El sistema de IA fue entrenado con redes neuronales profundas (DCNN) como ResNet-50, que aprendieron a identificar los signos característicos del neumotórax en las imágenes, incluso sin contar con anotaciones manuales completas. A través de mapas de activación (heatmaps), el modelo puede señalar las regiones donde es probable que exista aire libre en la cavidad torácica.En términos de rendimiento, el modelo alcanzó un AUC de 0.7891, situándose entre los mejores resultados del conjunto de enfermedades. En las tareas de localización, logró una precisión del 45.9% bajo criterios amplios, superando ampliamente a métodos anteriores como MetaMap, que apenas alcanzaban un 32% de precisión.La detección automática de neumotórax mediante IA, como lo plantea ChestX-ray8, ofrece un soporte esencial en situaciones donde un diagnóstico rápido puede salvar vidas. Su implementación en sistemas de triaje automatizado o como segunda lectura médica tiene un gran potencial clínico, especialmente en áreas críticas o con acceso limitado a especialistas.",
    ruta: "img8.png"
  }
];
  selectedDisease: any = {
    name: "",
    explanation: "Esta plataforma web de apoyo diagnóstico utiliza un sistema de Inteligencia Artificial entrenado con el conjunto de datos ChestX-ray8, que contiene más de 100,000 radiografías de tórax. Mediante el uso de una red neuronal convolucional profunda (CNN), el sistema es capaz de detectar automáticamente enfermedades torácicas comunes como Atelectasia, Cardiomegalia, Derrame pleural, Infiltración pulmonar, Masa, Nódulo, Neumonía y Neumotórax.El modelo fue entrenado sobre la arquitectura DenseNet121, especializada en imágenes médicas, y se encarga de predecir la probabilidad de presencia de cada enfermedad a partir de una imagen de rayos X. Al cargar una imagen en la plataforma, el sistema la procesa, genera un diagnóstico con los tres hallazgos más probables, y proporciona una explicación médica automática, además de una versión en audio generado con voz sintética.Toda la información se almacena en una base de datos para mantener un historial clínico accesible, lo que convierte esta herramienta en un sistema útil para entornos hospitalarios o educativos, combinando procesamiento de imágenes, lenguaje natural y síntesis de voz.",
    ruta: "imgPrincipal.png"
  };
  selctDefect(){
    this.selectedDisease= {
    name: "",
    explanation: "Esta plataforma web de apoyo diagnóstico utiliza un sistema de Inteligencia Artificial entrenado con el conjunto de datos ChestX-ray8, que contiene más de 100,000 radiografías de tórax. Mediante el uso de una red neuronal convolucional profunda (CNN), el sistema es capaz de detectar automáticamente enfermedades torácicas comunes como Atelectasia, Cardiomegalia, Derrame pleural, Infiltración pulmonar, Masa, Nódulo, Neumonía y Neumotórax.El modelo fue entrenado sobre la arquitectura DenseNet121, especializada en imágenes médicas, y se encarga de predecir la probabilidad de presencia de cada enfermedad a partir de una imagen de rayos X. Al cargar una imagen en la plataforma, el sistema la procesa, genera un diagnóstico con los tres hallazgos más probables, y proporciona una explicación médica automática, además de una versión en audio generado con voz sintética.Toda la información se almacena en una base de datos para mantener un historial clínico accesible, lo que convierte esta herramienta en un sistema útil para entornos hospitalarios o educativos, combinando procesamiento de imágenes, lenguaje natural y síntesis de voz.",
    ruta: "imgPrincipal.png"
  };
  }
  selectDisease(disease: any) {
    this.selectedDisease = disease;
  }
}